from classes.IR import IRS

ir_system = IRS(500)
# text_all_file = ir_system.read_all_row()
# list_token = ir_system.tokenizer(text_all_file)
# list_clean_token = ir_system.clean_word(list_token)
# print("answer 1:\n", list_clean_token, "\n")
# dict_token = ir_system.generate_stopwords(list_clean_token)
# list_rank = ir_system.add_value_to_list(dict_token)
# sorted_dict = ir_system.sort_dict(dict_token, list_rank, 55)
# print("answer 2:\n", sorted_dict, "\n")
text_title_and_plot = ir_system.read_title_and_plot()
list_tokenize_title_and_plot = ir_system.tokenize_title_and_plot(text_title_and_plot)
posting_title_and_plot = ir_system.posting_title_and_plot(list_tokenize_title_and_plot)
print("answer 3:\n", posting_title_and_plot, "\n")
